#!/bin/sh
set -e


# =========================================
# Build type
# =========================================
KBE_CONFIG=${1:-Release}
echo "[INFO] Using build type: $KBE_CONFIG"

# =========================================
# Basic tools and dependencies (macOS)
# =========================================
if ! command -v git >/dev/null 2>&1; then
    echo "[ERROR] Git is not installed."
    echo "[INFO] Please install Git first, then rerun this script."
    echo "[INFO] Official site: https://git-scm.com/download/mac"
    echo "[INFO] Tutorial: https://docs.github.com/en/get-started/git-basics/set-up-git"
    exit 1
fi

if ! command -v brew >/dev/null 2>&1; then
    echo "[ERROR] Homebrew is not installed."
    echo "[INFO] Please install Homebrew first, then rerun this script."
    echo "[INFO] Official site: https://brew.sh/"
    echo "[INFO] Install guide: https://docs.brew.sh/Installation"
    exit 1
fi

if ! command -v xcode-select >/dev/null 2>&1; then
    echo "[ERROR] xcode-select is not available."
    echo "[INFO] Please install Xcode Command Line Tools first, then rerun this script."
    echo "[INFO] Run: xcode-select --install"
    echo "[INFO] Apple docs: https://developer.apple.com/download/all/"
    exit 1
fi

if ! xcode-select -p >/dev/null 2>&1; then
    echo "[ERROR] Xcode Command Line Tools are not installed."
    echo "[INFO] Please install them first, then rerun this script."
    echo "[INFO] Run: xcode-select --install"
    echo "[INFO] Apple docs: https://developer.apple.com/download/all/"
    exit 1
fi

install_brew_dep() {
    PKG="$1"
    if brew list --formula "$PKG" >/dev/null 2>&1; then
        echo "[INFO] $PKG is already installed"
        return 0
    fi

    echo "[INFO] Installing $PKG via Homebrew..."
    brew install "$PKG"
}

install_brew_dep cmake
install_brew_dep ninja
install_brew_dep autoconf
install_brew_dep automake
install_brew_dep libtool
install_brew_dep pkg-config
install_brew_dep libtirpc
install_brew_dep zstd

BREW_PREFIX="$(brew --prefix)"
ZSTD_PREFIX="$(brew --prefix zstd)"

export LDFLAGS="-L$ZSTD_PREFIX/lib ${LDFLAGS:-}"
export CPPFLAGS="-I$ZSTD_PREFIX/include ${CPPFLAGS:-}"

check_required_tool() {
    TOOL_NAME="$1"
    if ! command -v "$TOOL_NAME" >/dev/null 2>&1; then
        echo "[ERROR] $TOOL_NAME was not found in PATH after Homebrew installation."
        echo "[INFO] Please ensure Homebrew bin directory is in PATH, then rerun."
        echo "[INFO] Example for Apple Silicon: export PATH=\"/opt/homebrew/bin:$PATH\""
        exit 1
    fi
}

check_required_tool cmake
check_required_tool ninja
check_required_tool pkg-config

# =========================================
# Check GitHub accessibility
# =========================================
echo "[CHECK] Trying to access GitHub repository..."
if ! git ls-remote https://github.com/microsoft/vcpkg.git >/dev/null 2>&1; then
    echo "[ERROR] Cannot access GitHub repository, please check network or proxy"
    echo "[INFO] You can also use the domestic proxy mirror, try running install/proxy/install_macos.sh."
    exit 1
fi
echo "[SUCCESS] GitHub repository is accessible"



# =========================================
# Install vcpkg
# =========================================
VCPKG_DIR="$HOME/kbe-vcpkg"
if [ ! -d "$VCPKG_DIR" ] || [ ! -f "$VCPKG_DIR/bootstrap-vcpkg.sh" ]; then
    echo "[INFO] Cloning vcpkg"
    git clone https://github.com/microsoft/vcpkg.git "$VCPKG_DIR"
else
    echo "[INFO] vcpkg already exists: $VCPKG_DIR"
fi


git -C "$VCPKG_DIR" reset --hard HEAD
git -C "$VCPKG_DIR" pull


NINJA_BIN=$(command -v ninja)
export CMAKE_MAKE_PROGRAM="$NINJA_BIN"


OLDPWD=$(pwd)
cd "$VCPKG_DIR"
./bootstrap-vcpkg.sh
cd "$OLDPWD"


export CMAKE_MAKE_PROGRAM="$NINJA_BIN"
# =========================================
# Build KBEngine-Nex
# =========================================
echo "[INFO] Entering ../kbe/src/"
cd "$(dirname "$0")/../kbe/src/"

# If the existing build dir was generated by another backend (e.g. Unix Makefiles),
# clean it to avoid generator mismatch when switching to Ninja.
if [ -f build/CMakeCache.txt ] && ! grep -q "CMAKE_GENERATOR:INTERNAL=Ninja" build/CMakeCache.txt; then
    echo "[INFO] Existing build directory uses a non-Ninja generator, recreating build/"
    rm -rf build
fi

echo "[INFO] Configuring CMake"
cmake -G Ninja -B build -S . \
    -DCMAKE_MAKE_PROGRAM="$NINJA_BIN" \
    -DCMAKE_TOOLCHAIN_FILE="$VCPKG_DIR/scripts/buildsystems/vcpkg.cmake" \
    -DKBE_CONFIG="$KBE_CONFIG"

echo "[INFO] Building KBEngine-Nex"
cmake --build build --parallel

echo "[INFO] Installation complete"
